// "use client";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { Footer, Navbar } from "@/components";

// import {NFTMarketProvider } from "@/context/NFTMarketContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {





  return (

    <html lang="en">
      <body className={inter.className}>
        {/* <NFTMarketProvider> */}

        <Navbar/>
        {children}
        <Footer/>
      {/* </NFTMarketProvider> */}
      </body>
    </html>
  );
}
